### ISSUE TITLE
Error: Cannot find module './get-first-page'

### ISSUE THREAD

**Issue by davidsbond** [taichi/ci-yarn-upgrade#105]
Hello, I'm using `ci-yarn-upgrade` to keep a project of mine up-to-date. Recently, it started producing this error on the nightly runs:

```bash
yarn run v1.13.0
$ ci-yarn-upgrade --execute --prefix feature/
{ Error: Cannot find module './get-first-page'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at paginationPlugin (/src/node_modules/@octokit/rest/lib/plugins/pagination/index.js:4:26)
    at plugin (/src/node_modules/@octokit/rest/index.js:24:33)
    at Array.forEach (<anonymous>)
    at new GitHubApi (/src/node_modules/@octokit/rest/index.js:28:11)
    at new exports.default (/src/node_modules/ci-yarn-upgrade/lib/github.js:168:25)
    at git.remoteurl.then.remote (/src/node_modules/ci-yarn-upgrade/lib/upgrade-request.js:12:1288) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

It's managing to create the branch fine, but is producing this error when trying to open the pull request

**Comment by taichi** [comment]
i can't reproduce this error. but i fix some of pagination warning.
and i released 0.7.6. please check it.

**Comment by davidsbond** [comment]
Thanks for the quick response, I will give it a go!

**Comment by davidsbond** [comment]
@taichi Looks like this is an issue with the `octokit` library rather than yours. After doing a manual `yarn upgrade` in my repository it's working again.
