### ISSUE TITLE
リポジトリのURLが正しく生成されなくなった

### ISSUE THREAD

**Issue by abcang** [taichi/ci-yarn-upgrade#91]
10月末頃から、npmjsから新しくインストールしたci-yarn-upgrade(version 0.6.3)を実行すると、リポジトリのURLが正しく生成されずにタグの一覧の取得やプルリクエストの作成が動かなくなりました。

https://circleci.com/gh/taichi/ci-yarn-upgrade/348

```
> BEGIN reconcile CompareModel @octokit/rest
> BEGIN getTags from https://git+https/github.com/octokit/rest.js
> BEGIN reconcile CompareModel commander
> BEGIN getTags from https://git+https/github.com/tj/commander.js
> BEGIN reconcile CompareModel eslint
> BEGIN getTags from https://git+https/github.com/eslint/eslint
> BEGIN reconcile CompareModel git-url-parse
> BEGIN getTags from https://git+ssh/git@github.com/IonicaBizau/git-url-parse
> BEGIN reconcile CompareModel lodash
> BEGIN getTags from https://git+https/github.com/lodash/lodash
> END   getTags [object Object] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
> END   reconcile CompareModel @octokit/rest
> END   getTags [object Object] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
> END   reconcile CompareModel git-url-parse
> END   getTags [object Object] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
> END   reconcile CompareModel lodash
> END   getTags [object Object] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
> END   reconcile CompareModel commander
> END   getTags [object Object] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
> END   reconcile CompareModel eslint
> BEGIN Send PullRequest.
{ HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
    at response.text.then.message (/usr/local/share/.config/yarn/global/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  code: 404,
  status: 'Not Found',
  headers:
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers':
      'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
     connection: 'close',
     'content-encoding': 'gzip',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Wed, 31 Oct 2018 13:00:42 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '404 Not Found',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'transfer-encoding': 'chunked',
     'x-accepted-oauth-scopes': 'repo',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'C8C8:6C41:2749E2:5AA447:5BD9A77A',
     'x-oauth-scopes': 'repo',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4988',
     'x-ratelimit-reset': '1540994401',
     'x-xss-protection': '1; mode=block' } }
```

どうやら依存しているライブラリが更新された影響らしく、各パッケージを最新に更新すると正しく動くようになりました。ライブラリを更新して新しいバージョンを公開してもらえると幸いです。
https://github.com/taichi/ci-yarn-upgrade/tree/yarn-upgrade/20181031010030/ef476465cfb1f8fb9253d024d582adbfd4e828f5

**Comment by taichi** [comment]
対応したものをリリースしました。ご確認下さい。

**Comment by abcang** [comment]
対応ありがとうございます。新しいバージョンで試してみたところgit-url-parseが10系のままのため、まだ正しいURLが生成できませんでした。
git-url-parseを11.0.1にアップデートしたところ正しいURLが生成できるようになったので、プルリクエストを作りました。よろしくお願いします。

#92

**Comment by taichi** [comment]
PRをマージしてリリースしました。

**Comment by abcang** [comment]
正しく動くようになりました。ありがとうございました。
